openapi: 3.1.0
info:
  title: Astro Weekday API
  version: "1.0.0"
  description: |
    🔮 API สำหรับตรวจสอบวันจริง และคำนวณข้อมูลโหราศาสตร์เบื้องต้น  
    รองรับทั้งวันที่รูปแบบไทย (พ.ศ.) และสากล (ค.ศ.)  
    สร้างด้วย FastAPI + Flatlib

servers:
  - url: https://astro-weekday-api.vercel.app   # ⚠️ เปลี่ยนชื่อโดเมนให้ตรงกับของคุณ

paths:
  /api/weekday:
    get:
      operationId: getWeekday
      summary: ตรวจสอบวันจริงจากวันที่ (ไทย/สากล)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "10/10/2568"
          description: วันที่รูปแบบ DD/MM/YYYY (พ.ศ. หรือ ค.ศ.)
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    example: "10/10/2568"
                  weekday:
                    type: string
                    example: "ศุกร์"
                  resolved_gregorian:
                    type: string
                    example: "2025-10-10"
                  calendar:
                    type: string
                    example: "BE"

  /api/astro-weekday:
    get:
      operationId: getAstroWeekday
      summary: ตรวจสอบวันจริง + เวลา + timezone + สถานที่เกิด (เพื่อใช้ในโหราศาสตร์)
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
          description: วันที่รูปแบบ DD/MM/YYYY
        - name: time
          in: query
          required: false
          schema:
            type: string
            example: "11:00"
          description: เวลา (HH:MM)
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
          description: โซนเวลา (IANA timezone เช่น Asia/Bangkok, Europe/London)
        - name: place
          in: query
          required: false
          schema:
            type: string
            example: "Bangkok"
          description: สถานที่เกิด (optional)
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  date: { type: string, example: "24/11/2514" }
                  time: { type: string, example: "11:00" }
                  timezone: { type: string, example: "Asia/Bangkok" }
                  weekday: { type: string, example: "พุธ" }
                  resolved_gregorian: { type: string, example: "1971-11-24" }
                  calendar: { type: string, example: "BE" }
                  local_datetime: { type: string, example: "1971-11-24T11:00:00+07:00" }
                  utc_datetime: { type: string, example: "1971-11-24T04:00:00+00:00" }
                  place: { type: string, example: "Bangkok" }

  /api/astro-chart:
    get:
      operationId: getAstroChart
      summary: คำนวณตำแหน่งดวงดาวจริง (Flatlib)
      description: |
        คำนวณตำแหน่งดาวเคราะห์หลัก (Sun, Moon, Mercury, Venus, Mars, Jupiter, Saturn, Ascendant)
        จากวันเวลาและสถานที่เกิด
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            example: "24/11/2514"
        - name: time
          in: query
          required: true
          schema:
            type: string
            example: "11:00"
        - name: timezone
          in: query
          required: false
          schema:
            type: string
            example: "Asia/Bangkok"
        - name: lat
          in: query
          required: false
          schema:
            type: number
            example: 13.75
        - name: lon
          in: query
          required: false
          schema:
            type: number
            example: 100.5
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  input:
                    type: object
                    properties:
                      date: { type: string, example: "24/11/2514" }
                      time: { type: string, example: "11:00" }
                      timezone: { type: string, example: "Asia/Bangkok" }
                      lat: { type: number, example: 13.75 }
                      lon: { type: number, example: 100.5 }
                  planets:
                    type: object
                    example:
                      Sun: { sign: "Scorpio", lon: 240.55 }
                      Moon: { sign: "Gemini", lon: 73.12 }
                      Mercury: { sign: "Sagittarius", lon: 252.44 }
                      Venus: { sign: "Libra", lon: 203.25 }
                      Mars: { sign: "Cancer", lon: 101.88 }
                      Jupiter: { sign: "Scorpio", lon: 231.55 }
                      Saturn: { sign: "Gemini", lon: 85.33 }
                      Ascendant: { sign: "Capricorn", lon: 293.15 }
